### ISSUE TITLE
Cupy with wavelet transform

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [PyLops/pylops_swungrendezvous2021#1]
Hello!

I am trying to use Cupy with FISTA algorithm and wavelet transform for seismic regularization, but I got the following error: "Argument 'b' has incorrect type (expected cupy._core.core.ndarray, got numpy.ndarray)"

I share my google Colab with the error: https://colab.research.google.com/drive/1PBKtrubgtQ0eAVhITUGgUj5uE6nqTF-S#scrollTo=7EDyiT5KYzCC

Thank you!

**Comment by cako** [comment]
Hi! Although I can't access your notebook, from the error my guess is that you are trying to pass a Numpy array to a function which requires a CuPy array. Here is an example of how to bring an array to GPU:

```python
x_cpu = np.array([1, 2, 3])
x_gpu = cp.asarray(x_cpu)
```

Hope this helps!

**Comment by AlejaHernandezRojas** [comment]
> Hi! Although I can't access your notebook, from the error I guess that you are trying to pass a Numpy array to a function which requires a CuPy array. Here is an example of how to bring an array to GPU:
> 
> ```python
> x_cpu = np.array([1, 2, 3])
> x_gpu = cp.asarray(x_cpu)
> ```
> 
> Hope this helps!

I just shared with you the colab. I did what you mention but it does not work. I hope you can check the notebook, thanks!

**Comment by mrava87** [comment]
Hi,
See my reply to the other issue on pylops-gpu.

Unfortunately a small portion of operators is not yet available in the gpu/cupy backend: https://pylops.readthedocs.io/en/latest/gpu.html

The DWT is one of them as we use PyWavelets and we are not aware of any gpu/cupy implementation out there. Looking at your notebook though, I would suggest to first make things work nicely on CPU. Moving to GPUs makes sense only if you start dealing with 3D data, on 2D data you won’t get any considerable speed up as there is just not enough computations to do for the GPU to shine ;)

**Comment by cako** [comment]
Yup, that's exactly what is happening. @AlejaHernandezRojas is trying to use the Seislet transform which is not yet on GPU.

**Comment by AlejaHernandezRojas** [comment]
So I can not use cupy with wavelet transform? 

Thanks @cako and @mrava87

**Comment by mrava87** [comment]
Hi @AlejaHernandezRojas,
no. To be more precise, cupy is a very nice library mapping pretty much all functionalities of numpy into GPU compatible code. If you have a numpy based code it is pretty easy to adapt it to use cupy and so GPU (this is what we did for most of Pylops). But pylops relies on some specialized libraries (like PyWavelets) that wrap C code into Python, in that case there is no easy win, someone would need to rewrite the algorithm entirely on GPU compatible code - in this case, the few operators I mentioned, we have not done so ourselves (this is a very big task) and so you cannot so far take advantage of GPUs in this case.

However looking at your notebook, if your goal is to use GPUs I would reccomend you to look at https://pylops.readthedocs.io/en/latest/api/generated/pylops.signalprocessing.ChirpRadon2D.html#pylops.signalprocessing.ChirpRadon2D as a good alternative to wavelet/seislet as sparsifying transform (it actually works best in our experience): see  https://pylops.readthedocs.io/en/latest/tutorials/seismicinterpolation.html#sphx-glr-tutorials-seismicinterpolation-py and notebook referred at the bottom for an example on how to use it :)

**Comment by PAULGOYES** [comment]
Hi @mrava87, I was wondering if there is a way to export the operator to numpy array (RWop = Rop*Wop.H). Because In that way it can be easy to implement in CUPY.

**Comment by mrava87** [comment]
Hi,
I am not sure what you mean, you want to export the output of the chained operator?

**Comment by cako** [comment]
Hi everyone,

What I believe @PAULGOYES is suggesting is to convert the operator to a dense matrix, so that the matrix representing the operator can be sent to the GPU. Unfortunately, for any but the smallest problem, this is not viable. In the example that @AlejaHernandezRojas provided, the operator in dense matrix form occupies 6Gb of RAM (24576*32768 elements), which kills the session when I try to convert to a CuPy array. Not only that, but it would require 24576 applications of the forward function of the operator which would likely take a very long time.

The whole point of PyLops is to substitute dense matrix representations by fast functions which compute matrix-vector products. You don't need a convolution matrix (`convmtx(a)`) to perform convolution: you can do `ifft(fft(a)*fft(b))` which is much faster. Unfortunately this also means that someone has to write the functions. So the whereas "best" solution would be to write the wavelet library in a GPU-compliant manner, the most practical solution is to use a transform *which already is provided* in a GPU-compliant manner. The latter is what @mrava87 was suggesting with the `ChirpRadon2D` transform.

**Comment by PAULGOYES** [comment]
Hi @cako  and @mrava87  thanks, yes you are right. The dense matrix is too big.
We will try some examples with ChirpRadon2D. I am working with @AlejaHernandezRojas . Soon we will share our example for seismic regularization in cross-spread domain.

**Comment by cako** [comment]
Great! Looking forward to seeing it!

**Comment by mrava87** [comment]
Nice, looking forward to seeing your results 😎
